/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "chatProject_constants.h"

namespace ChatProject {

const chatProjectConstants g_chatProject_constants;

chatProjectConstants::chatProjectConstants() {
}

} // namespace

