/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "chatProject_constants.h"

namespace ChatProject {

const chatProjectConstants g_chatProject_constants;

chatProjectConstants::chatProjectConstants() {
}

} // namespace

