/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ChatProject;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * List Msg Id
 */
public class MsgIdList implements org.apache.thrift.TBase<MsgIdList, MsgIdList._Fields>, java.io.Serializable, Cloneable, Comparable<MsgIdList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MsgIdList");

  private static final org.apache.thrift.protocol.TField MSG_ID_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("msgIdList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MsgIdListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MsgIdListTupleSchemeFactory());
  }

  public List<Long> msgIdList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MSG_ID_LIST((short)1, "msgIdList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MSG_ID_LIST
          return MSG_ID_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MSG_ID_LIST, new org.apache.thrift.meta_data.FieldMetaData("msgIdList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MsgIdList.class, metaDataMap);
  }

  public MsgIdList() {
  }

  public MsgIdList(
    List<Long> msgIdList)
  {
    this();
    this.msgIdList = msgIdList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MsgIdList(MsgIdList other) {
    if (other.isSetMsgIdList()) {
      List<Long> __this__msgIdList = new ArrayList<Long>(other.msgIdList);
      this.msgIdList = __this__msgIdList;
    }
  }

  public MsgIdList deepCopy() {
    return new MsgIdList(this);
  }

  @Override
  public void clear() {
    this.msgIdList = null;
  }

  public int getMsgIdListSize() {
    return (this.msgIdList == null) ? 0 : this.msgIdList.size();
  }

  public java.util.Iterator<Long> getMsgIdListIterator() {
    return (this.msgIdList == null) ? null : this.msgIdList.iterator();
  }

  public void addToMsgIdList(long elem) {
    if (this.msgIdList == null) {
      this.msgIdList = new ArrayList<Long>();
    }
    this.msgIdList.add(elem);
  }

  public List<Long> getMsgIdList() {
    return this.msgIdList;
  }

  public MsgIdList setMsgIdList(List<Long> msgIdList) {
    this.msgIdList = msgIdList;
    return this;
  }

  public void unsetMsgIdList() {
    this.msgIdList = null;
  }

  /** Returns true if field msgIdList is set (has been assigned a value) and false otherwise */
  public boolean isSetMsgIdList() {
    return this.msgIdList != null;
  }

  public void setMsgIdListIsSet(boolean value) {
    if (!value) {
      this.msgIdList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MSG_ID_LIST:
      if (value == null) {
        unsetMsgIdList();
      } else {
        setMsgIdList((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MSG_ID_LIST:
      return getMsgIdList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MSG_ID_LIST:
      return isSetMsgIdList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MsgIdList)
      return this.equals((MsgIdList)that);
    return false;
  }

  public boolean equals(MsgIdList that) {
    if (that == null)
      return false;

    boolean this_present_msgIdList = true && this.isSetMsgIdList();
    boolean that_present_msgIdList = true && that.isSetMsgIdList();
    if (this_present_msgIdList || that_present_msgIdList) {
      if (!(this_present_msgIdList && that_present_msgIdList))
        return false;
      if (!this.msgIdList.equals(that.msgIdList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(MsgIdList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMsgIdList()).compareTo(other.isSetMsgIdList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMsgIdList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.msgIdList, other.msgIdList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MsgIdList(");
    boolean first = true;

    sb.append("msgIdList:");
    if (this.msgIdList == null) {
      sb.append("null");
    } else {
      sb.append(this.msgIdList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MsgIdListStandardSchemeFactory implements SchemeFactory {
    public MsgIdListStandardScheme getScheme() {
      return new MsgIdListStandardScheme();
    }
  }

  private static class MsgIdListStandardScheme extends StandardScheme<MsgIdList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MsgIdList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MSG_ID_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.msgIdList = new ArrayList<Long>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  long _elem10;
                  _elem10 = iprot.readI64();
                  struct.msgIdList.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setMsgIdListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MsgIdList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.msgIdList != null) {
        oprot.writeFieldBegin(MSG_ID_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.msgIdList.size()));
          for (long _iter11 : struct.msgIdList)
          {
            oprot.writeI64(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MsgIdListTupleSchemeFactory implements SchemeFactory {
    public MsgIdListTupleScheme getScheme() {
      return new MsgIdListTupleScheme();
    }
  }

  private static class MsgIdListTupleScheme extends TupleScheme<MsgIdList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MsgIdList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMsgIdList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMsgIdList()) {
        {
          oprot.writeI32(struct.msgIdList.size());
          for (long _iter12 : struct.msgIdList)
          {
            oprot.writeI64(_iter12);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MsgIdList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.msgIdList = new ArrayList<Long>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            long _elem15;
            _elem15 = iprot.readI64();
            struct.msgIdList.add(_elem15);
          }
        }
        struct.setMsgIdListIsSet(true);
      }
    }
  }

}

