/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef chatProject_CONSTANTS_H
#define chatProject_CONSTANTS_H

#include "chatProject_types.h"

namespace ChatProject {

class chatProjectConstants {
 public:
  chatProjectConstants();

};

extern const chatProjectConstants g_chatProject_constants;

} // namespace

#endif
